config/routes.rb
Rails.application.routes.draw do
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  
  resources :contacts
  
  get '/instagram-printer', to: 'pages#printer'
  
  get '/livefeed', to: 'pages#livefeed'
  
  
  
  get '/testnav', to: 'pages#testnav'
  
  root 'pages#homepage'
  
  
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, :email, :comments, presence: true
    
    after_create :send_email
    
    private
    def send_email
        if self.contact_type == "maincontact_hire"
            ContactMailer.contact_email(self).deliver
        
        elsif
            self.contact_type == "partners_hire"
            ContactMailer.partner_email(self).deliver
            
        elsif 
            self.contact_type == "printer_hire"
            ContactMailer.printer_email(self).deliver

        else
            ContactMailer.livefeed_email(self).deliver
        
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale
  
  # if Rails.env.production?

  #     before_filter :authenticate

  #     protected

  #     def authenticate
  #       authenticate_or_request_with_http_basic do |username, password|
  #         username == "jd2015" && password == "jd2015"
  #       end
  #     end
  #   end
    
  private
    def allow_iframe
      response.headers.delete "X-Frame-Options"
    end

    def set_locale
      if cookies[:sp_locale] && I18n.available_locales.include?(cookies[:sp_locale].to_sym)
        l = cookies[:sp_locale].to_sym
      else
        l = I18n.default_locale
        cookies.permanent[:sp_locale] = l
      end
      I18n.locale = l
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            render json: nil
        else
            render json: { errors: @contact.errors }, status: :bad_request
        end
    end
    
    private
    def contact_params
       params.require(:contact).permit(:name, :email, :phone, :comments, :contact_type) 
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    after_filter :allow_iframe
    
    def homepage
    end
    
    def printer_page
    end
    
    def livefeed
    end
    
    def gifpage
    end
    
    def selfies
    end
    
    def testnav
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:sp_locale] = l
    redirect_to request.referer || root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<!--<%= form_for @contact do |f| %>-->
<!--    <%= f.text_field :name, placeholder: "Name" %>-->
<!--    <%= f.email_field :email, placeholder: "Email" %>-->
<!--    <%= f.telephone_field :phone, placeholder: "Phone" %>-->
<!--    <%= f.text_area :comments, placeholder: "Message" %>-->
<!--    <%= f.submit "Submit" %>-->
<!--<% end %>-->

<%= render partial: 'contacts/partials/form', locals: { contact_type: 'become_partner' }  %>

app/views/contacts/partials/_form.html.erb
<%= form_tag contacts_path, class: "contact-form", remote: true do %>
    <div class="form-content">
        <%= hidden_field_tag 'contact[contact_type]', contact_type %>
        <%= text_field_tag 'contact[name]', nil, placeholder: "NAME", class: "name-field" %>
        <%= telephone_field_tag 'contact[phone]', nil, placeholder: "PHONE", class: "phone-field" %>
        <%= email_field_tag 'contact[email]', nil, placeholder: "EMAIL", class: "email-field" %>
        <%= text_area_tag 'contact[comments]', nil, placeholder: "COMMENTS", class: "comments-field" %>
        <%= submit_tag "SUBMIT", class: "form-submit-button" %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container center">
        <p>© COPYRIGHT 2016 SOCIAL PLAYGROUND.</p>
    </div>
</footer>

app/views/layouts/_nav.html.erb
             <!-------------------------------------------->
             <!--          NavBar Section                -->
             <!--------------------------------------------> 




<div class="navcontainer navbar-dropdown">
    <div class="nav-elements">
        <ul class="dropdown-ul">
            <li class="dropdown-main-li">
                <a class="nav-item" ><img class="dropdown-image" src="<%= asset_path( 'menu-dropdown-icon.png' ) %>"></a>
                <div class="nav-content">
                    <div class="nav-sub">
                        <ul>
                            <a href="/"><li class="home-li"><p class="home-p ddlink">Home</p></li></a>
                            <a href="/#toys"><li class="toys-li"><p class="toys-p ddlink">Toys</p></li></a>
                            <a href="/#past-events"><li class="pastevents-li"><p class="pastevents-p ddlink">Past Events</p></li></a>
                            <a href="/#contact"><li class="contact-li"><p class="contact-p ddlink">Contact</p></li></a>
                            <a href="/#partners"><li class="partners-li"><p class="partners-p ddlink">Partners</p></li></a>
                            <%= link_to change_locale_path(:id) do %>
                              <li class="lang-li"><p class="lang-p ddlink">ID</p></li>
                            <% end %>
                            <%= link_to change_locale_path(:en) do %>
                              <li class="lang-li"><p class="lang-p ddlink">EN</p></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
        <a href="/"><img class="logo-main" src="<%= asset_path('social-playground-logo.png')%>"></a>
    </div>
</div>             <!-----------------  /Dropdown Navbar Section   ----------------->



<div class="navcontainer navbar-desktop">
    <div class="nav-elements">
        <a href="#"><img src="<%= asset_path('social-playground-logo.png')%>"></a>
        <div class="lang-switcher">
          <%= link_to 'ID', change_locale_path(:id)%>
          |
          <%= link_to 'EN', change_locale_path(:en)%>
        </div>

        <div class="nav-list">
            <ul class="nav-ul">
                <li><a href="/" class="home-link">Home</a></li>
                <li><a href="/#toys" class="toys-link" id="toys-scroll-link">Toys</a></li>
                <li><a href="/#past-events" class="pastevents-link">Past Events</a></li>
                <li><a href="/#contact" class="contact-link">Contact</a></li>
                <li><a href="/#partners" class="partners-link">Partners</a></li>
            </ul>
        </div>
    </div>
</div>              <!-----------------  /Desktop Navbar Section   ----------------->

    

app/views/layouts/_navigation.html.erb
<nav>
  <div class="container nav-container">
    <div class="row">
      <div class="nav-wrapper">
        <a href="#" id="brand-logo" class="col l2"><img src="<%= asset_path('social-playground-logo.png')%>"></a>
        <ul id="nav-mobile" class=" col l10 right hide-on-med-and-down nav-desktop">
          <li><a id="link-home" href="">Home</a></li>
          <li><a id="link-toys" href="">Toys</a></li>
          <li><a id="link-pastevents" href="">Past Events</a></li>
          <li><a id="link-contacts" href="">Contacts</a></li>
          <li><a id="link-partners" href="">Partners</a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', cache: true %>
  <%= csrf_meta_tags %>
  <title><%= yield(:title) %> | Social Playground</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scaleable=no">
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="Live Digital Experiences for brand activations, corporate events and weddings." name="description">
	<%= favicon_link_tag 'favicon-16x16.png' %>
</head>
<body id="top">

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/livefeed.html.erb
<% provide(:title, "Live Feed") %>

<body>
    
    <div class="livefeed-hero-section">
        <%= render 'layouts/nav' %>    
        <a href="https://www.facebook.com/socialplaygroundindonesia/?fref=ts&ref=br_tf" target="_blank"><p class="facebook-social"></p></a>
        <!--<a href="https://twitter.com/socialplaygrnd" target="_blank"><p class="twitter-social"></p></a>-->
        <a href="https://www.instagram.com/socialplayground_id/" target="_blank"><p class="instagram-social"></p></a>
        <%= image_tag('livefeed/carousel01-big (3).jpg', class: 'livefeed-hero-image') %>
        <h3 class="livefeed-hero-quote">LIVE FEED</h3>
        <h5 class="livefeed-hero-text">SNAP. TAG. STREAM.</h5>
    
    </div>
    
    <div class="livefeed-quote1">
        <h2>Real Time Fun</h2>
    </div>
    
    <div class="stp-icon-section round-shadow">
        <div class="icon snap-icon-section">
            <p class="sprite livefeed-snap-sprite"></p>
            <span class="stp-icon-header">Snap</span>
            <span class="stp-icon-text"><%= raw t('take_photo_to_instagram') %></span>
        </div>
        <div class="icon tag-icon-section">
            <p class="sprite livefeed-tag-sprite"></p>
            <span class="stp-icon-header">Tag</span>
            <span class="stp-icon-text"><%= raw t('add_hash_tag') %></span>
        </div>
        <div class="icon print-icon-section">
            <p class="sprite livefeed-stream-sprite"></p>
            <span class="stp-icon-header">Stream</span>
            <span class="stp-icon-text"><%= raw t('stream_the_images') %></span>
        </div>
    </div>
    
    
    <div class="stp-icon-section-small round-shadow">
        <div class="snap-icon-section">
            <p class="livefeed-snap"></p>
            <span class="stp-icon-header">Snap</span>
            <span class="stp-icon-text"><%= raw t('take_photo_to_instagram') %></span>
        </div>
        
        <div class="tag-icon-section">
            <p class="livefeed-tag"></p>
            <span class="stp-icon-header">Tag</span>
            <span class="stp-icon-text"><%= raw t('add_hash_tag') %></span>
        </div>
        
        <div class="print-icon-section">
            <p class="livefeed-stream"></p>
            <span class="stp-icon-header">Stream</span>
            <span class="stp-icon-text-stream">Stream the images on</br>an event screen, instantly.</span>
        </div>
    </div>
    
    
    <div class="livefeed-facts-section">
        <%= image_tag('livefeed/live-feed-goals-bg.jpg', class: 'main-bg-image') %>
        <div class="section-main-text">
            <h2 class="main-section-heading">Engage in Real</br>time sharing</h2>
            <p class="main-section-body"><%= raw t('put_attendees') %></p>
        </div>
        <%= image_tag('livefeed/live-feed01.jpg', class: 'centre-image') %>
        <div class="section-facts-text">
            <h3 class="fact-heading"><%= raw t('beautifull_displays') %></h3>
            <p class="fact-info"><%= raw t('showcase_content') %></p>
            <h3 class="fact-heading"><%= raw t('protect_reputation') %></h3>
            <p class="fact-info"><%= raw t('need_control') %></p>
            <h3 class="fact-heading"><%= raw t('post_engagement') %></h3>
            <p class="fact-info"><%= raw t('continue_conversation') %></p>
        </div>
    </div>
    
    <div class="livefeed-strip-large">
        <%= image_tag('livefeed/feed01 (1).jpg') %>
        <%= image_tag('livefeed/feed02 (1).jpg') %>
        <%= image_tag('livefeed/feed03 (1).jpg') %>
        <%= image_tag('livefeed/feed04 (1).jpg') %>
        <%= image_tag('livefeed/feed05 (1).jpg') %>
    </div>
    
    
    <div class="livefeed-strip-small">
        <%= image_tag(('livefeed/feed02 (1).jpg'), class: 'img1') %>
        <%= image_tag(('livefeed/feed03 (1).jpg'), class: 'img2') %>
        <%= image_tag(('livefeed/feed05 (1).jpg'), class: 'img3') %>
    </div>
    
    
    
    
    <!--<div class="livefeed-page-cta">-->
    <!--    <h2>Want the live feed</br>at your next event?</h2>-->
    <!--    <%= link_to "Hire Now", root_path, class: "live-feed-hire-link" %>-->
    <!--</div>-->
    
    <div class="livefeed-form-div">
        <div class="livefeed-form-text">
            <h2>Want the live feed</br>at your next event?</h2>
        </div>
        <div class="livefeed-form-section">
            <a class="livefeedhire-button enquire-button"><span>Hire Now</span></a>
            <p class="livefeed-form-scrollpoint form-close"><%= image_tag('close-icon-white.png') %></p>
            <%= render partial: 'contacts/partials/form', locals: { contact_type: 'livefeed_hire' } %>
        </div>
    </div>
    
    
    
    <div class="livefeed-page-printer-cta">
        <h2>Like the live feed?</br>check out our instagram printer</h2>
        <%= link_to "Instagram Printer", instagram_printer_path, class: "printer-hire-link" %>
    </div>
</body>

app/views/pages/printer.html.erb
<% provide(:title, "Instagram Printer") %>

<body class="printer-body">

<div class="printerpage-hero-section" id="arrow-scroll">
    <%= render 'layouts/nav' %>
    <a href="https://www.facebook.com/socialplaygroundindonesia/?fref=ts&ref=br_tf" target="_blank"><p class="facebook-social"></p></a>
    <!--<a href="https://twitter.com/socialplaygrnd" target="_blank"><p class="twitter-social"></p></a>-->
    <a href="https://www.instagram.com/socialplayground_id/" target="_blank"><p class="instagram-social"></p></a>
    <h3 class="printer-hero-quote">LIVE INSTAGRAM PRINTER</h3>
    <h5 class="printer-hero-text">SNAP. TAG. PRINT.</h5>
</div>

<div class="how-to-play-section">
    <span class="how-to-play-quote">How to play</span>
</div>

<div class="stp-icon-section round-shadow">
    <div class="icon">
        <p class="sprite printer-snap-sprite"></p>
        <span class="stp-icon-header">Snap</span>
        <span class="stp-icon-text"><%= raw t('take_photo_to_instagram') %></span>
    </div>
    <div class="icon">
        <p class="sprite printer-tag-sprite"></p>
        <span class="stp-icon-header">Tag</span>
        <span class="stp-icon-text"><%= raw t('add_hash_tag') %></span>
    </div>
    <div class="icon">
        <p class="sprite printer-print-sprite"></p>
        <span class="stp-icon-header">Print</span>
        <span class="stp-icon-text"><%= raw t('collect_photo') %></span>
    </div>
</div>

<div class="stp-icon-section-small round-shadow">
    <div class="snap-icon-section">
        <%= image_tag('printer/snap-icon.png') %>
        <span class="stp-icon-header">Snap</span>
        <span class="stp-icon-text-printer"><%= raw t('take_photo_to_instagram') %></span>
    </div>
    
    <div class="tag-icon-section">
        <%= image_tag('printer/tag-icon.png') %>
        <span class="stp-icon-header">Tag</span>
        <span class="stp-icon-text"><%= raw t('add_hash_tag') %></span>
    </div>
    
    <div class="print-icon-section">
        <%= image_tag('printer/print-icon.png') %>
        <span class="stp-icon-header">Print</span>
        <span class="stp-icon-text"><%= raw t('collect_photo') %></span>
    </div>
</div>


<div class="video-container">
  <iframe width="853" height="480" src="https://player.vimeo.com/video/157413601" frameborder="0" allowfullscreen></iframe>
</div>

<div class="about-printer-section">
    <div class="printer-facts">
        <p class="printer-facts-heading"><%= raw t('spread_content') %></p>
        <p class="printer-facts-body"><%= raw t('inspire_attendees') %></p>
        
        <p class="printer-facts-heading"><%= raw t('drive_hash_tag') %></p>
        <p class="printer-facts-body"><%= raw t('incentivize_consumers') %></p>
        
        <p class="printer-facts-heading"><%= raw t('engage_via_offers') %></p>
        <p class="printer-facts-body"><%= raw t('integrate_hash_tag') %></p>
        
        <p class="printer-facts-heading"><%= raw t('post_content') %></p>
        <p class="printer-facts-body"><%= raw t('well_provide_photo') %></p>
    </div>
</div>



<div class="printer-img-highlight-section">
    <h2 class="printer-highlight-heading">The Printer</h2>
    <ul class="printer-image-ul">
        <div class="image-row-1">
            <li><%= image_tag ("printer/instagram-printer01.jpg") %></li>
            <li><%= image_tag ("printer/instagram-printer02.jpg") %></li>
            <li><%= image_tag ("printer/instagram-printer03.jpg") %></li>
        </div>
        <div class="image-row-2">
            <li><%= image_tag ("printer/instagram-printer04.jpg") %></li>
            <li><%= image_tag ("printer/instagram-printer05.jpg") %></li>
            <li><%= image_tag ("printer/instagram-printer06.jpg") %></li>
        </div>
    </ul>
</div>

<div class="printer-live-feed-strip">
    <ul class="live-feed-strip">
        <li class="img1"><%= image_tag("printer/feed01.jpg") %></li>
        <li class="img2"><%= image_tag("printer/feed02.jpg") %></li>
        <li class="img3"><%= image_tag("printer/feed03.jpg") %></li>
        <li class="img4"><%= image_tag("printer/feed04.jpg") %></li>
        <li class="img5"><%= image_tag("printer/feed05.jpg") %></li>
    </ul>
</div>

<div class="printer-live-feed-strip-small">
    <ul class="live-feed-strip">
        <li class="img1"><%= image_tag("printer/feed01.jpg") %></li>
        <li class="img2"><%= image_tag("printer/feed02.jpg") %></li>
        <li class="img3"><%= image_tag("printer/feed04.jpg") %></li>
    </ul>
</div>

<!--<div class="instagram-printer-cta-section form-div">-->
<!--    <h2>Want the Instagram Printer</br>at your next event?</h2>-->
<!--    <a class="printerhire-button enquire-button"><span>Hire Now</span></a>-->
<!--    <p class="printerhire-form-scrollpoint"><%= image_tag('close-icon-white.png') %></p>-->
<!--    <%= render partial: 'contacts/partials/form', locals: { contact_type: 'printer_hire' } %>-->

<!--</div>-->


<div class="printer-form-div">
    <div class="printer-form-text">
        <h2>Want the Instagram Printer</br>at your next event?</h2>
    </div>
    <div class="printer-form-section">
        <a class="printerhire-button enquire-button"><span>Hire Now</span></a>
        <p class="printerhire-form-scrollpoint form-close"><%= image_tag('close-icon-white.png') %></p>
        <%= render partial: 'contacts/partials/form', locals: { contact_type: 'printer_hire' } %>
    </div>
</div>




<div class="printer-live-feed-cta">
    <%#= image_tag('printer/live-feed-cta.jpg', class: "printer-live-feed-background-image") %>
        <h2><%= raw t('like_the_printer') %></h2>
        <%= link_to "Live Feed", livefeed_path, class: "live-feed-hire-link" %>
</div>


</body>